version: '3.9'

services:

  db:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./mount:/var/lib/postgresql/data:rw
      - ./my_scripts:/root/src:ro
    networks:
      - db-net

  adminer:
    image: "adminer"
    ports:
      - "8081:8080"
    networks:
      - db-net

  helios:
    image: "adminer"
    # ports:
    #   - "8080:8080"
    network_mode: "host"
    

networks:
  db-net: